/**
 * This file represents the Types generated from the OpenAPI spec.
 * In a real CI/CD, this would be auto-generated by `openapi-typescript`.
 */

export interface ApiErrorResponse {
  code: string;
  message: string;
  details?: Record<string, any>;
}

export interface LoginRequest {
  email?: string;
  password?: string;
  phone?: string; // ILMA specific
}

export interface LoginResponse {
  token: string;
  user: any; // Mapped to User type in core types
}

export interface SyncPayload {
  items: Array<{
    id: string;
    type: string;
    payload: any;
    timestamp: number;
  }>;
}

export interface SyncResponse {
  processedIds: string[];
  failedIds: Array<{ id: string; error: string }>;
}

// --- Client Error Types ---

export enum ErrorCode {
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
  TIMEOUT = 'TIMEOUT',
  UNKNOWN = 'UNKNOWN'
}

export class ApiClientError extends Error {
  public code: ErrorCode;
  public status: number;
  public details?: any;

  constructor(message: string, code: ErrorCode, status: number = 0, details?: any) {
    super(message);
    this.name = 'ApiClientError';
    this.code = code;
    this.status = status;
    this.details = details;
  }
}
