"""add_scheduled_purge_and_content_reports

Revision ID: 720b33690c58
Revises: a1p2q3r4s5t6
Create Date: 2026-04-12 03:20:21.242464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '720b33690c58'
down_revision: Union[str, Sequence[str], None] = 'a1p2q3r4s5t6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_profile_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('INSULT', 'CHEATING', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_reports_reporter_id'), 'content_reports', ['reporter_id'], unique=False)
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_analytics_session_id'), table_name='analytics_events')
    op.create_index(op.f('ix_analytics_events_profile_id'), 'analytics_events', ['profile_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.alter_column('challenges', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_content_versions_content_type_content_id'), table_name='content_versions')
    op.drop_index(op.f('ix_domains_name_trgm'), table_name='domains', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('exam_sub_questions', 'depends_on_previous',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_micro_lessons_status'), table_name='micro_lessons')
    op.drop_index(op.f('ix_micro_lessons_title_trgm'), table_name='micro_lessons', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('uq_student_micro_skill'), 'micro_skill_progress', type_='unique')
    op.create_unique_constraint('uq_profile_micro_skill', 'micro_skill_progress', ['profile_id', 'micro_skill_id'])
    op.drop_constraint(op.f('plans_tier_key'), 'plans', type_='unique')
    op.add_column('profiles', sa.Column('scheduled_purge_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('profiles', 'weekly_goal_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('120'))
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_text_trgm'), table_name='questions', postgresql_ops={'text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_skills_name_trgm'), table_name='skills', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=False)
    op.drop_index(op.f('uq_weekly_leaderboard_profile_week'), table_name='weekly_leaderboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_weekly_leaderboard_profile_week'), 'weekly_leaderboard', ['profile_id', 'week_iso'], unique=True)
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.create_index(op.f('ix_skills_name_trgm'), 'skills', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_questions_text_trgm'), 'questions', ['text'], unique=False, postgresql_ops={'text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.alter_column('profiles', 'weekly_goal_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('120'))
    op.drop_column('profiles', 'scheduled_purge_at')
    op.create_unique_constraint(op.f('plans_tier_key'), 'plans', ['tier'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_profile_micro_skill', 'micro_skill_progress', type_='unique')
    op.create_unique_constraint(op.f('uq_student_micro_skill'), 'micro_skill_progress', ['student_id', 'micro_skill_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_micro_lessons_title_trgm'), 'micro_lessons', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_micro_lessons_status'), 'micro_lessons', ['status'], unique=False)
    op.alter_column('exam_sub_questions', 'depends_on_previous',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_domains_name_trgm'), 'domains', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_content_versions_content_type_content_id'), 'content_versions', ['content_type', 'content_id'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.alter_column('challenges', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_profile_id'), table_name='analytics_events')
    op.create_index(op.f('ix_analytics_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keys_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fail_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('push_subscriptions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('push_subscriptions_pkey'))
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], unique=True)
    op.drop_index(op.f('ix_content_reports_reporter_id'), table_name='content_reports')
    op.drop_table('content_reports')
    # ### end Alembic commands ###
